name: CICD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  #github actions의 탬플릿(자동으로 pull받음)
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Verify files and directories
        run: |
          echo "Current directory:"
          pwd
          echo "Files in current directory:"
          ls -al

      - name: Build with Gradle
        run: |
          mkdir -p ./src/main/resources
          echo ${{ secrets.APPLICATION }} | base64 --decode > ./src/main/resources/application.yml
          echo ${{ secrets.APPLICATION_PROD }} | base64 --decode > ./src/main/resources/application-prod.yml
          echo ${{ secrets.APPLICATION_LOCAL }} | base64 --decode > ./src/main/resources/application-local.yml
          chmod 777 ./gradlew
          ./gradlew clean build -x test  #jar파일 생성

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker (create Docker image)
        run: docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/ceos_vote .
      - name: Push Docker
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ceos_vote:latest
        
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:         
      - name: Docker compose  #ec2로 이동해서 ec2에 접속
        uses: appleboy/ssh-action@master
        with:
          username: ubuntu
          host: ${{ secrets.VOTE_SERVER_IP }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ceos_vote
            sudo docker ps -q --filter "name=ceos_vote" | grep -q . && sudo docker stop ceos_vote && sudo docker rm ceos_vote || true
            sudo docker run -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/ceos_vote
    
